### ISSUE TITLE
Translated PyRaylib-specific Documentation

### ISSUE THREAD

**Issue by SamyBencherif** [Ho011/pyraylib#4]
### Introduction.

This project should be cherished as it's one of the fastest/easiest ways to bootstrap a graphical/3D application. There's documentation to be found all kinds of places (raylib, source, CLI doc), but I did not find a pyraylib-specific html/pdf reference doc. 

I know many Raylib developers will surely be comfortable using the source of this project combined with raylib.h or the cheatsheet pdf as a full reference documentation.

And a lot of our experienced Python friends will be fine with using the `help` function to get a nicely formated CLI document about the Window Class. (Though it must be done via a source file, because this module doesn't like to be imported by shell)

But since this is such a special project, bridging two technologies that were inherently designed to be fun yet powerful, I think it deserves its very own reference documents.

### Statement.

I am electing to take what I know about Raylib -- and some of my own opinions about documentation and readability -- to create a special set of documentation designed for new pyraylib users.

### Plans.

1. The documentation will be accessible via static single page HTML
2. "" via interactive HTML page with convenience organizational features 
3. An empty window project template available for download
4. (stretch) A spinning cube project template available for download
5. (stretch) Any additional project templates will be behind a "more" button

### Integration/Hosting.

I can host this on my website. Or it can be within GH Wiki for this repo or a fork.
In a perfect world, new users can find the docs from the GH readme, and the PYPI index.

### **Action Item.**

I suggest one of the following would be a logical next step !

1. Assign this issue to my user account
2. Tell me you rather I make a fork of the project first

**Comment by 7s9n** [comment]
@SamyBencherif thank you so much for your proposal, and I'm sorry i did not see your issue earlier, so I assigned this issue to you, I appreciate your work .💛
